name: Build Android and iOS
on: push

jobs:
  install-and-test:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x]
    steps: 
      - uses: actions/checkout@v2
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install npm dependencies
        run: |
          yarn install 
      - name: run tests
        run: |
          yarn test
