version: '3'
services:
  api:
    container_name: api
    build: ./api
    restart: always
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./api:/var/www/api
      - ./api/data:/var/data/
    env_file: .env
    # command: uwsgi --socket 0.0.0.0:5000 --protocol=http --wsgi-file wsgi.py
    command: python3 wsgi.py
  redis:
    container_name: redis
    image: redis
